application: zakitenem
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- appstats: on

handlers:
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /_ah/spi/.*
  script: main.application
  
libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: ssl
  version: latest
 
